import{S as L,i as m,a as w}from"./assets/vendor-4c86d853.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&d(c)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerpolicy&&(o.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?o.credentials="include":t.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function d(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const v=document.querySelector(".form"),g=document.querySelector('input[type="text"]'),u=document.querySelector(".gallery"),S=document.querySelector(".loader"),f=document.querySelector(".load-btn"),A="40876862-5828b09b8a35d05d7759eed0a",p=40;let a=1,y=0,h="",l=[];const k={icon:"icon-false",backgroundColor:"#FC5A5A",message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#FAFAFB",messageSize:"16px",position:"topRight",close:!1},I=async()=>(await w.get("https://pixabay.com/api",{params:{key:A,q:h,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:p,page:a}})).data,b=async()=>{try{const e=await I();if(y=e.totalHits,e.hits.length===0)return r("none"),s("none"),m.show(k);q(e)}catch(e){console.error(e.message)}},q=e=>{l=e.hits.map(n=>`
    <li class="gallery-item">
      <a href="${n.largeImageURL}">
        <img class="api-img" src="${n.webformatURL}" alt="${n.tags}">
        <div class="img-desc">
          <span><b>Likes:</b> <br/>${n.likes}</span>
          <span><b>Views:</b> <br/>${n.views}</span>
          <span><b>Comments:</b> <br/>${n.comments}</span>
          <span><b>Downloads:</b> <br/>${n.downloads}</span>
        </div>
      </a>
    </li>
              `),u.insertAdjacentHTML("beforeend",l.join("")),s("inline-block"),C(),F(),P.refresh()},r=e=>{S.style.display=e},s=e=>{f.style.display=e},F=()=>{if(a>1){const e=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e.height*2.4,left:0,behavior:"smooth"})}},C=()=>{if(Math.ceil(y/p)===a)return s("none"),m.show({icon:"icon-false",backgroundColor:"#FC5A5A",message:"We're sorry, but you've reached the end of search results.",messageColor:"#FAFAFB",messageSize:"16px",position:"topRight",close:!1})};g.addEventListener("input",e=>{h=e.target.value});v.addEventListener("submit",async e=>{e.preventDefault(),s("none"),l=[],a=1,u.innerHTML="",r("inline-block"),await b(),l.length>0&&s("inline-block"),r("none"),g.value=""});f.addEventListener("click",async()=>{s("none"),r("inline-block"),a+=1,await b(),r("none")});const P=new L(".gallery a",{overlayOpacity:0,captionsData:"alt",captionDelay:250});
//# sourceMappingURL=commonHelpers2.js.map
